# yaml-language-server: $schema=https://cdn.jsdelivr.net/gh/compose-spec/compose-spec@master/schema/compose-spec.json

services:
  app:
    image: golang:1.22-buster # Image page: <https://hub.docker.com/_/golang>
    working_dir: /src
    environment:
      HOME: /tmp
      GOPATH: /tmp
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/src:cached
      - tmp-data:/tmp:cached
    security_opt: [no-new-privileges:true]

  golint:
    image: golangci/golangci-lint:v1.61-alpine # Image page: <https://hub.docker.com/r/golangci/golangci-lint>
    environment:
      GOLANGCI_LINT_CACHE: /tmp/golint # <https://github.com/golangci/golangci-lint/blob/v1.42.0/internal/cache/default.go#L68>
    volumes:
      - .:/src:ro
      - golint-go:/go:rw # go dependencies will be downloaded on each run without this
      - golint-cache:/tmp/golint:rw
    working_dir: /src
    security_opt: [no-new-privileges:true]

volumes:
  tmp-data: {}
  golint-go: {}
  golint-cache: {}
