version: '3.2'

volumes:
  tmp-data:

services:
  app:
    image: golang:1.13-alpine # Image page: <https://hub.docker.com/_/golang>
    working_dir: /src
    environment:
      HOME: '/tmp'
      PS1: '\[\033[1;32m\]\[\033[1;36m\][\u@docker] \[\033[1;34m\]\w\[\033[0;35m\] \[\033[1;36m\]# \[\033[0m\]'
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./src:/src:cached
      - ./build:/build:cached
      - tmp-data:/tmp:cached
